module.exports = {
  WELCOME: 'WELCOME',
  GAP_ANALYSIS: 'GAP_ANALYSIS',
  MOCK_INTERVIEW: 'MOCK_INTERVIEW',
  TECH_QUIZ: 'TECH_QUIZ',
  RESUME_BUILDING: 'RESUME_BUILDING',
  CAREER_COUNSELLING: 'CAREER_COUNSELLING'
};
